/***************************************************************************
                          cadsurfview.h  -  description
                             -------------------
    begin                : Mon Feb 17 13:05:59 IST 2003
    copyright            : (C) 2003 by Sharjith
    email                : sharjith_ssn@hotmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef CADSURFVIEW_H
#define CADSURFVIEW_H

// include files for Qt
#include "QGLView.h"
#include <qlabel.h>
#include <qstring.h>
#include <qdatetime.h>
#include <qtimer.h>
#include <qgl.h>
#include <qvbox.h>

class CadSurfDoc;

/**
 * This class provides an incomplete base for your application view.
 * 	
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 * @version KDevelop version 1.1 code generation
 */
class CadSurfView : public QGLWidget
{
	Q_OBJECT
	friend class CadSurfDoc;

public:
    /** Constructor for the view
    	* @param pDoc  your document instance that the view represents. Create a document before calling the constructor
    	* or connect an already existing document to a new MDI child widget.*/
    CadSurfView(CadSurfDoc* pDoc, QWidget* parent, const char *name, int wflags);
    /** Destructor for the main view */
    ~CadSurfView();
		/** returns a pointer to the document connected to the view*/
    CadSurfDoc *getDocument() const;
    /** gets called to redraw the document contents if it has been modified */
		void update(CadSurfView* pSender);
    /** contains the implementation for printing functionality and gets called by CadSurfApp::slotFilePrint() */
    void print(QPrinter *pPrinter);
		
protected:
	virtual void closeEvent(QCloseEvent*);
	virtual void initializeGL();
	virtual void resizeGL(int w, int h);
	virtual void paintGL();
	CadSurfDoc *doc;

private:
	void DrawRectangle (const int  MinX  ,
    					        const int  MinY  ,
                                const int  MaxX  ,
				    	        const int  MaxY  ,
					            const bool  Draw
                                );

public:
	bool winZoom;
	bool dShaded;
	bool antialiased;
	bool gridOn;
	QLabel *coordViewer;
private:
	bool ldown;
	bool mdown;
	bool rdown;
				
	QPoint  lPoint;
	QPoint  mPoint;
	QPoint  rPoint;	
		
	int     myXmin;
    int     myYmin;
    int     myXmax;
    int     myYmax;

    QString dtStr, tmStr;
    QTime tm; QDate dt;
	
protected:
	void mousePressEvent( QMouseEvent *);
  	void mouseReleaseEvent( QMouseEvent *);
  	void mouseMoveEvent( QMouseEvent *);
  	void resizeEvent( QResizeEvent *);
public:
	void SetDisplayMode(const GLDisplayMode& aMode);
	GLDisplayMode GetDisplayMode() const { return myView->GetDisplayMode(); }
	QGLView* GetView() const { return myView; }
private:
	QGLView* myView;
private slots:
	void slotUpdateTime();
	
};

#endif
