#############################################################################
# Makefile for building: cadsurf
# Generated by qmake (1.07a) (Qt 3.3.8) on: Tue Nov 12 19:40:26 2024
# Project:  CadSurf.pro
# Template: app
# Command: $(QMAKE) -o Makefile CadSurf.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -g  -D'VERSION="5.0"' -DQT_CLEAN_NAMESPACE -DQT_SHARED -DQT_NO_DEBUG
CXXFLAGS = -pipe -Wall -W -g  -D'VERSION="5.0"' -DQT_CLEAN_NAMESPACE -DQT_SHARED -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/home/sharjith/Downloads/qt-x11-free-3.3.8/mkspecs/default -I. -I. -I/ -I. -I/home/sharjith/include -I$(QTDIR)/include -I/usr/X11R6/include -I/usr/X11R6/include -I.ui/ -I.moc/
LINK     = g++
LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -L/usr/X11R6/lib -L/home/sharjith/lib64 -lVKGeom -lVKGraphic -lVKCollection -lglut -lqt -lGLU -lGL -lXmu -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = .obj/

####### Files

HEADERS = CadSurf.h \
		CadSurfDoc.h \
		CadSurfView.h \
		MaterialDlg.ui.h \
		MDIWindow.h \
		GLDisplayContext.cpp \
		UserSurface.h \
		QGLView.h
SOURCES = CadSurf.cpp \
		CadSurfDoc.cpp \
		CadSurfView.cpp \
		main.cpp \
		MDIWindow.cpp \
		GLDisplayContext.cpp \
		UserSurface.cpp \
		QGLView.cpp
OBJECTS = .obj/CadSurf.o \
		.obj/CadSurfDoc.o \
		.obj/CadSurfView.o \
		.obj/main.o \
		.obj/MDIWindow.o \
		.obj/GLDisplayContext.o \
		.obj/UserSurface.o \
		.obj/QGLView.o \
		.obj/MaterialDlg.o \
		.obj/GridSettings.o
FORMS = MaterialDlg.ui \
		GridSettings.ui
UICDECLS = .ui/MaterialDlg.h \
		.ui/GridSettings.h
UICIMPLS = .ui/MaterialDlg.cpp \
		.ui/GridSettings.cpp
SRCMOC   = .moc/moc_CadSurf.cpp \
		.moc/moc_CadSurfDoc.cpp \
		.moc/moc_CadSurfView.cpp \
		.moc/moc_MDIWindow.cpp \
		.moc/moc_MaterialDlg.cpp \
		.moc/moc_GridSettings.cpp
OBJMOC = .obj/moc_CadSurf.o \
		.obj/moc_CadSurfDoc.o \
		.obj/moc_CadSurfView.o \
		.obj/moc_MDIWindow.o \
		.obj/moc_MaterialDlg.o \
		.obj/moc_GridSettings.o
DIST	   = CadSurf.pro
QMAKE_TARGET = cadsurf
DESTDIR  = 
TARGET   = cadsurf

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: CadSurf.pro  /home/sharjith/Downloads/qt-x11-free-3.3.8/mkspecs/default/qmake.conf /home/sharjith/Downloads/qt-x11-free-3.3.8/lib/libqt.prl
	$(QMAKE) -o Makefile CadSurf.pro
qmake: 
	@$(QMAKE) -o Makefile CadSurf.pro

dist: 
	@mkdir -p .obj/cadsurf && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .obj/cadsurf/ && $(COPY_FILE) --parents MaterialDlg.ui.h .obj/cadsurf/ && ( cd `dirname .obj/cadsurf` && $(TAR) cadsurf.tar cadsurf && $(GZIP) cadsurf.tar ) && $(MOVE) `dirname .obj/cadsurf`/cadsurf.tar.gz . && $(DEL_FILE) -r .obj/cadsurf

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

.obj/CadSurf.o: CadSurf.cpp CadSurfView.h \
		CadSurfDoc.h \
		CadSurf.h \
		MDIWindow.h \
		res/appicon.xpm \
		res/filenew.xpm \
		res/fileopen.xpm \
		res/filesave.xpm \
		res/top.xpm \
		res/bottom.xpm \
		res/front.xpm \
		res/back.xpm \
		res/left.xpm \
		res/right.xpm \
		res/axo.xpm \
		res/reset.xpm \
		res/fitall.xpm \
		res/zoomwin.xpm \
		res/dmode.xpm \
		res/hlr.xpm \
		res/antial.xpm \
		res/points.xpm \
		res/line.xpm \
		res/circle.xpm \
		res/ellipse.xpm \
		res/parabola.xpm \
		res/hyperbola.xpm \
		res/bezier.xpm \
		res/bspline.xpm \
		res/plane.xpm \
		res/cylinder.xpm \
		res/cone.xpm \
		res/sphere.xpm \
		res/torus.xpm \
		res/extruded.xpm \
		res/revolved.xpm \
		res/ruled.xpm \
		res/pipe.xpm \
		res/translate.xpm \
		res/rotate.xpm \
		res/scale.xpm \
		res/reflect.xpm \
		.ui/GridSettings.h \
		.ui/MaterialDlg.h \
		QGLView.h \
		GLDisplayContext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/CadSurf.o CadSurf.cpp

.obj/CadSurfDoc.o: CadSurfDoc.cpp CadSurfDoc.h \
		CadSurf.h \
		CadSurfView.h \
		UserSurface.h \
		GLDisplayContext.h \
		QGLView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/CadSurfDoc.o CadSurfDoc.cpp

.obj/CadSurfView.o: CadSurfView.cpp CadSurfView.h \
		CadSurfDoc.h \
		CadSurf.h \
		QGLView.h \
		GLDisplayContext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/CadSurfView.o CadSurfView.cpp

.obj/main.o: main.cpp CadSurf.h \
		GLDisplayContext.h \
		QGLView.h \
		CadSurfDoc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o main.cpp

.obj/MDIWindow.o: MDIWindow.cpp MDIWindow.h \
		CadSurfView.h \
		QGLView.h \
		GLDisplayContext.h \
		CadSurfDoc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/MDIWindow.o MDIWindow.cpp

.obj/GLDisplayContext.o: GLDisplayContext.cpp GLDisplayContext.h \
		QGLView.h \
		CadSurfDoc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/GLDisplayContext.o GLDisplayContext.cpp

.obj/UserSurface.o: UserSurface.cpp CadSurf.h \
		UserSurface.h \
		GLDisplayContext.h \
		QGLView.h \
		CadSurfDoc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/UserSurface.o UserSurface.cpp

.obj/QGLView.o: QGLView.cpp QGLView.h \
		CadSurfDoc.h \
		GLDisplayContext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/QGLView.o QGLView.cpp

.ui/MaterialDlg.h: MaterialDlg.ui 
	$(UIC) MaterialDlg.ui -o .ui/MaterialDlg.h

.ui/MaterialDlg.cpp: .ui/MaterialDlg.h MaterialDlg.ui MaterialDlg.ui.h 
	$(UIC) MaterialDlg.ui -i MaterialDlg.h -o .ui/MaterialDlg.cpp

.ui/GridSettings.h: GridSettings.ui 
	$(UIC) GridSettings.ui -o .ui/GridSettings.h

.ui/GridSettings.cpp: .ui/GridSettings.h GridSettings.ui 
	$(UIC) GridSettings.ui -i GridSettings.h -o .ui/GridSettings.cpp

.obj/MaterialDlg.o: .ui/MaterialDlg.cpp MaterialDlg.ui.h \
		.ui/MaterialDlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/MaterialDlg.o .ui/MaterialDlg.cpp

.obj/GridSettings.o: .ui/GridSettings.cpp .ui/GridSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/GridSettings.o .ui/GridSettings.cpp

.obj/moc_CadSurf.o: .moc/moc_CadSurf.cpp  CadSurf.h GLDisplayContext.h \
		QGLView.h \
		CadSurfDoc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_CadSurf.o .moc/moc_CadSurf.cpp

.obj/moc_CadSurfDoc.o: .moc/moc_CadSurfDoc.cpp  CadSurfDoc.h GLDisplayContext.h \
		QGLView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_CadSurfDoc.o .moc/moc_CadSurfDoc.cpp

.obj/moc_CadSurfView.o: .moc/moc_CadSurfView.cpp  CadSurfView.h QGLView.h \
		GLDisplayContext.h \
		CadSurfDoc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_CadSurfView.o .moc/moc_CadSurfView.cpp

.obj/moc_MDIWindow.o: .moc/moc_MDIWindow.cpp  MDIWindow.h CadSurfView.h \
		QGLView.h \
		GLDisplayContext.h \
		CadSurfDoc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_MDIWindow.o .moc/moc_MDIWindow.cpp

.obj/moc_MaterialDlg.o: .moc/moc_MaterialDlg.cpp  .ui/MaterialDlg.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_MaterialDlg.o .moc/moc_MaterialDlg.cpp

.obj/moc_GridSettings.o: .moc/moc_GridSettings.cpp  .ui/GridSettings.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_GridSettings.o .moc/moc_GridSettings.cpp

.moc/moc_CadSurf.cpp: $(MOC) CadSurf.h
	$(MOC) CadSurf.h -o .moc/moc_CadSurf.cpp

.moc/moc_CadSurfDoc.cpp: $(MOC) CadSurfDoc.h
	$(MOC) CadSurfDoc.h -o .moc/moc_CadSurfDoc.cpp

.moc/moc_CadSurfView.cpp: $(MOC) CadSurfView.h
	$(MOC) CadSurfView.h -o .moc/moc_CadSurfView.cpp

.moc/moc_MDIWindow.cpp: $(MOC) MDIWindow.h
	$(MOC) MDIWindow.h -o .moc/moc_MDIWindow.cpp

.moc/moc_MaterialDlg.cpp: $(MOC) .ui/MaterialDlg.h
	$(MOC) .ui/MaterialDlg.h -o .moc/moc_MaterialDlg.cpp

.moc/moc_GridSettings.cpp: $(MOC) .ui/GridSettings.h
	$(MOC) .ui/GridSettings.h -o .moc/moc_GridSettings.cpp

####### Install

install:  

uninstall:  

